# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x, 16.x, 14.x]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install modules
        run: npm ci
      - name: Build files
        run: npm run build
      - name: Run tests
        run: npm run test -- --coverage --ci
      - name: Coverage Diff
        # You may pin to the exact commit or the version.
        # uses: GreatWizard/coverage-diff-action@a8493a0691192563017ec317e9879c9a17a4d36c
        uses: GreatWizard/coverage-diff-action@v1.0.8
        with:
          # A GitHub token to write comments and write the badge to the wiki.
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Path of the json-summary file to analyze.
          coverage-filename: coverage/coverage-final.json
          # Name of the json file containing the repository's default branch json-summary stored in the repo wiki.
          # base-summary-filename: # optional, default is base-summary.json
          # If true, it will not fail even if the current branch's coverage is lower than the default branch's coverage.
          # allowed-to-fail: # optional, default is false
          # Whether or not a badge will be generated and stored.
          # badge-enabled: # optional, default is true
          # Name of the json file containing badge informations stored in the repo wiki.
          # badge-filename: # optional, default is coverage-diff-badge.json
          # If the coverage percentage is above or equal to this value, the badge will be green.
          # badge-threshold-green: # optional, default is 100
          # If the coverage percentage is not green and above or equal to this value, the badge will be orange. Otherwise it will be red.
          # badge-threshold-orange: # optional, default is 70